### ISSUE TITLE
Modificaciones sugeridas al README

### ISSUE THREAD

**Issue by deantares** [mati3/Gestion-Medicamentos-IV#1]
"Idioma de programación" no es apropiado, se trata más bien de lenguaje de programación. Haz una prueba, busca en google entrecomillado ["idioma de programación"](https://www.google.es/search?ei=lf2hW5vcHuKRlwSbpZ-oCQ&q=%22idioma+de+programacion%22&oq=%22idioma+de+programacion%22&gs_l=psy-ab.3..0i7i30k1l8j0i8i7i30k1l2.50567.51183.0.51288.6.6.0.0.0.0.161.432.0j3.3.0....0...1c.1.64.psy-ab..5.1.152....0.rhrb77ZHC3Y) (62 resultados) y "[lenguaje de programación](https://www.google.es/search?q=%22lenguaje+de+programacion%22&oq=%22lenguaje&aqs=chrome.2.69i57j0j69i59j69i65l2j0.3222j0j7&sourceid=chrome&ie=UTF-8)" (>300.000 resultados).

Por otro lado, phpMyAdmin no es un motor de base de datos, es una herramienta de administración de servidores, que entre otros servicios permite administrar base de datos. Pero por si mismo, no es un motor de base de datos. Motores de base de datos son MySQL, MaríaDB, CouchDB, MongoDB, ...

**Comment by mati3** [comment]
modifico sugerencias closes #1
